- name: Package Flashable AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb 2>/dev/null || cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz 2>/dev/null || cp out/arch/arm64/boot/Image AnyKernel3/Image 2>/dev/null
          
          cat << 'EOF' > AnyKernel3/anykernel.sh
          ### AnyKernel3 Ramdisk Mod Script
          ## osm0sis @ xda-developers

          ### AnyKernel setup
          # global properties
          properties() { '
          kernel.string=KernelSU by Tech Mind
          do.devicecheck=0
          do.modules=0
          do.systemless=1
          do.cleanup=1
          do.cleanuponabort=0
          '; } # end properties

          ### AnyKernel install
          # boot files attributes
          boot_attributes() {
          set_perm_recursive 0 0 755 644 $RAMDISK/*;
          set_perm_recursive 0 0 750 750 $RAMDISK/init* $RAMDISK/sbin;
          } # end attributes

          # boot shell variables
          block=/dev/block/bootdevice/by-name/boot;
          [ -e "$block" ] || block=/dev/block/platform/soc/7824900.sdhci/by-name/boot;
          [ -e "$block" ] || block=/dev/block/platform/soc.0/7824900.sdhci/by-name/boot;
          [ -e "$block" ] || block=/dev/block/by-name/boot;
          is_slot_device=0;
          ramdisk_compression=auto;
          patch_vbmeta_flag=auto;

          # import functions/variables and setup patching - see for reference (DO NOT REMOVE)
          . tools/ak3-core.sh;

          # boot install
          split_boot;
          flash_boot;
          ## end boot install
          EOF

          cd AnyKernel3
          chmod -R 755 tools/ *.sh
          zip -r9 ../KernelSU-Redmi5A-Flashable.zip ./* -x .git README.md
